# Generated by Django 6.0.7 on 2026-07-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='elapsed_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
