# Generated by Django 6.0.7 on 2026-08-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0002_graph_elapsed_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='node_outputs',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
