# Generated by Django 6.0.7 on 2026-08-23 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0003_graph_node_outputs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineExecutionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='success', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('elapsed_seconds', models.FloatField(blank=True, null=True)),
                ('nodes_snapshot', models.JSONField(default=list)),
                ('node_outputs', models.JSONField(default=dict)),
                ('node_timings', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_runs', to='pipelines.pipeline')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('algorithm', models.CharField(max_length=100)),
                ('dataset_name', models.CharField(blank=True, max_length=255)),
                ('target_column', models.CharField(blank=True, max_length=255)),
                ('features', models.JSONField(default=list)),
                ('metrics', models.JSONField(default=dict)),
                ('preprocessing_steps', models.JSONField(default=list)),
                ('model_b64', models.TextField(blank=True)),
                ('model_format', models.CharField(default='pkl', max_length=20)),
                ('status', models.CharField(default='ready', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trained_models', to=settings.AUTH_USER_MODEL)),
                ('pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='pipelines.pipeline')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'name', 'version')},
            },
        ),
    ]
