# Generated by Django 6.0.7 on 2026-08-26 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0004_pipelineexecutionrun_trainedmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineexecutionrun',
            name='algorithm',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pipelineexecutionrun',
            name='dataset_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='pipelineexecutionrun',
            name='dataset_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pipelineexecutionrun',
            name='hyperparameters',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='pipelineexecutionrun',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='pipelineexecutionrun',
            name='metrics',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='pipelineexecutionrun',
            name='model_artifact_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='pipelineexecutionrun',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execution_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pipelineexecutionrun',
            name='pipeline_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pipelineexecutionrun',
            name='preprocessing_steps',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pipelineexecutionrun',
            name='random_seed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pipelineexecutionrun',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='pipelineexecutionrun',
            name='status',
            field=models.CharField(db_index=True, default='success', max_length=20),
        ),
        migrations.AddIndex(
            model_name='pipelineexecutionrun',
            index=models.Index(fields=['pipeline', '-start_time'], name='pipelines_p_pipelin_c3576c_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelineexecutionrun',
            index=models.Index(fields=['owner', '-start_time'], name='pipelines_p_owner_i_43d463_idx'),
        ),
    ]
